version: '3.9'

services:
  backend:
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    environment:
      - POSTGRES_DB=dbPoloIT
