services:

  backend_nodejs:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3030:3030
    depends_on: 
      db:
        condition: service_healthy

volumes:
  db_data:
