services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=BackPoloIT
      - NODE_ENV=production
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backend_nodejs:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3030:3030
    depends_on: 
      db:
        condition: service_healthy

volumes:
  db_data:
