services:
  backend_nodejs:
    env_file: ".env"
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - ${NODE_PORT}:3030
    networks:
     - ${NETWORK_NAME}

    command: ["npm","run","start"]