version: "3.9"
services:
  backend:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_DOCKER_PORT}/${DB_NAME}
    ports:
      - "${NODE_PORT}:${NODE_DOCKER_PORT}"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: ["npm","run","start"]

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "${DB_DOCKER_PORT}"

volumes:
  pgdata: