version: '3.9'

services:
  backend:
    command: sh -c "npm run build && npm run start"
    restart: always
    depends_on:
    - db
    ports:
      - "5050:3000"

  database:
    environment:
      - POSTGRES_DB=dbPoloIT
