version: "3.9"
services:
  backend:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=dbPoloIT
    ports:
      - "3652:3000"
    depends_on:
      - db
    

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbPoloIT
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5236:5432"

volumes:
  pgdata: